s_guest_freertos-objs-y = event_groups.o
s_guest_freertos-objs-y += heap_2.o
s_guest_freertos-objs-y += list.o
s_guest_freertos-objs-y += port.o
s_guest_freertos-objs-y += portASM.o
s_guest_freertos-objs-y += portZynq7000.o
s_guest_freertos-objs-y += queue.o
s_guest_freertos-objs-y += tasks.o
s_guest_freertos-objs-y += tick.o
s_guest_freertos-objs-y += timers.o
# s_guest_freertos-objs-y += inbyte.o
# s_guest_freertos-objs-y += outbyte.o
s_guest_freertos-objs-y += xscugic.o
s_guest_freertos-objs-y += xil_assert.o
s_guest_freertos-objs-y += xscugic_sinit.o
s_guest_freertos-objs-y += xscugic_g.o
